version: "3"

services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    volumes:
      - ./:/usr/src/app
      - ./:/srv/jekyll
    command: jekyll serve -s /usr/src/app --watch --verbose --trace
    ports:
      - "4000:4000"
    environment:
      TZ: Asia/Tokyo
