name: Build and Deploy to Netlify
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  TZ: Asia/Tokyo
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm packages
        run: npm ci
      - name: Generate index.json
        run: npm run generate-index

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-
      - name: Install utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install jq yq
      - name: Install dependencies
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          npm install terser -g
          curl -LO https://github.com/WebAssembly/binaryen/releases/download/version_119/binaryen-version_119-x86_64-linux.tar.gz
          tar -xzf binaryen-version_119-x86_64-linux.tar.gz
          sudo cp binaryen-version_119/bin/* /usr/local/bin/
      - name: Build wasm
        run: cargo run --features=bin index.json
        working-directory: tinysearch

      - name: Cache Modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: node-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Build Astro
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
